/* Replace with your SQL commands */
CREATE TABLE `movies` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `yify_id` INT(11) UNSIGNED NOT NULL,
    `torrent_json` JSON,
    `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `date_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

